const DIMENSIONS = ["action","social","rational","emotional","stability","curiosity","independence","empathy","competitiveness","adaptability"]
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function bandOf(v){if(v<30)return "very_low";if(v<45)return "low";if(v<60)return "mid";if(v<80)return "high";return "very_high"}
export function scoreAnswers(questionData,answers){
 const raw={},maxRaw={};DIMENSIONS.forEach(d=>{raw[d]=0;maxRaw[d]=0});const map={};questionData.questions.forEach(q=>{map[q.id]=q;DIMENSIONS.forEach(d=>{let b=0;q.options.forEach(o=>{const v=(o.scores&&o.scores[d])||0;if(v>b)b=v});maxRaw[d]+=b})});
 answers.forEach(a=>{const q=map[a.questionId];if(!q)return;const o=q.options[a.optionIndex];if(!o)return;DIMENSIONS.forEach(d=>raw[d]+=(o.scores&&o.scores[d])||0)});
 const normalized={};DIMENSIONS.forEach(d=>normalized[d]=maxRaw[d]?Math.round(raw[d]/maxRaw[d]*100):50);return{raw,maxRaw,normalized}}
function distance(u,p){let s=0;DIMENSIONS.forEach(d=>{const x=(u[d]||0)-(p[d]||0);s+=x*x});return Math.sqrt(s/DIMENSIONS.length)}
export function rankZodiacs(normalized,zodiacProfiles){const rows=zodiacProfiles.profiles.map(z=>{const d=distance(normalized,z.profile);return Object.assign({},z,{distance:d,match:Math.round(clamp(100-d*1.25,35,96))})});rows.sort((a,b)=>a.distance-b.distance);return rows}
function pickStyle(n){const x=[["观察型",(n.rational+n.empathy+n.stability)/3],["理性型",n.rational],["感受型",n.emotional],["行动型",n.action],["独立型",n.independence],["关系型",(n.empathy+n.social)/2]];x.sort((a,b)=>b[1]-a[1]);return x[0][0]}
function testBand(v,b){if(b==="high")return v>=60;if(b==="low")return v<45;if(b==="mid")return v>=45&&v<60;return false}
export function buildAnalysis(n,ranked,t){const p=ranked[0],s=ranked[1],third=ranked[2];const rows=DIMENSIONS.map(k=>({key:k,value:n[k]})).sort((a,b)=>b.value-a.value);const top=rows.slice(0,3);const style=pickStyle(n);const main=t.main_templates.find(x=>x.zodiac===p.key&&x.style===style);const pair=t.pair_templates.find(x=>x.primary===p.key&&x.secondary===s.key);const dimensionTexts=top.map(r=>t.dimension_templates.find(x=>x.dimension===r.key&&x.band===bandOf(r.value))).filter(Boolean);let contrast=null;for(let i=0;i<t.contrast_templates.length;i++){const c=t.contrast_templates[i];if(testBand(n[c.a],c.a_band)&&testBand(n[c.b],c.b_band)){contrast=c;break}}const scenes=["社交方式","亲密关系","工作学习","压力反应","决策方式","隐藏一面"].map((sc,i)=>t.scene_templates.find(x=>x.scene===sc&&x.dominant_dimension===top[i%top.length].key)).filter(Boolean);const sums=t.summary_templates.filter(x=>x.dimension===top[0].key);const summary=sums.length?sums[(p.key.length+s.key.length)%sums.length]:null;return{primary:{key:p.key,name:p.name,icon:p.icon,match:p.match,keywords:p.keywords},secondary:{key:s.key,name:s.name,icon:s.icon,match:s.match,keywords:s.keywords},third:{key:third.key,name:third.name,icon:third.icon,match:third.match,keywords:third.keywords},style,topDimensions:top,main,pair,dimensionTexts,contrast,scenes,summary,disclaimer:t.meta.disclaimer}}
export function getZodiacByDate(month,day,z){const md=month*100+day;let k="capricorn";if(md>=321&&md<=419)k="aries";else if(md<=520&&md>=420)k="taurus";else if(md<=621&&md>=521)k="gemini";else if(md<=722&&md>=622)k="cancer";else if(md<=822&&md>=723)k="leo";else if(md<=922&&md>=823)k="virgo";else if(md<=1023&&md>=923)k="libra";else if(md<=1122&&md>=1024)k="scorpio";else if(md<=1221&&md>=1123)k="sagittarius";else if(md>=1222||md<=119)k="capricorn";else if(md>=120&&md<=218)k="aquarius";else if(md>=219&&md<=320)k="pisces";return z.profiles.find(x=>x.key===k)}